/**
 * Phase-1 PDF Export Service
 * Client-side PDF generation using html2canvas + jsPDF
 * Desktop browser focus, low-risk implementation
 *
 * Based on: PDF Export Compatibility Analysis
 * Deferred: Mobile optimization, server-side, custom fonts (Phase-2+)
 */

import html2canvas from "html2canvas";
import { jsPDF } from "jspdf";
import type { ChartExportOptions, ReportExportOptions } from "./types";
import { PDF_LIMITS } from "./types";

/** Desktop-optimized scale (analysis §4.2, §7.1) - balance quality vs performance */
const DESKTOP_SCALE = 2;

/** Check if running in browser (SSR safety) */
function isBrowser(): boolean {
  return typeof window !== "undefined" && typeof document !== "undefined";
}

/** Detect mobile for quality scaling (analysis §4.3) */
function isMobileDevice(): boolean {
  if (!isBrowser()) return false;
  return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(
    navigator.userAgent
  );
}

/**
 * Memory-aware scale (analysis §4.3, §7.4):
 * - Desktop: scale 2
 * - iOS Safari: scale 1 (strict memory constraints)
 * - Other mobile: scale 2 if deviceMemory >= 4GB, else 1
 */
function getExportScale(): number {
  if (!isBrowser()) return DESKTOP_SCALE;
  if (!isMobileDevice()) return DESKTOP_SCALE;
  if (/iPhone|iPad|iPod/.test(navigator.userAgent)) return 1; // iOS: prefer stability
  const memory = (navigator as Navigator & { deviceMemory?: number }).deviceMemory;
  if (memory == null) return 1; // Unknown: prefer stability
  return memory >= 4 ? DESKTOP_SCALE : 1;
}

/**
 * Export a single chart element as PDF (Phase-1 primary path)
 * Captures DOM element via html2canvas, embeds in A4 PDF
 */
export async function exportChartAsPdf(
  options: ChartExportOptions
): Promise<void> {
  if (!isBrowser()) {
    throw new Error("PDF export requires browser environment");
  }

  const element = document.getElementById(options.elementId);
  if (!element) {
    throw new Error(`Element with ID "${options.elementId}" not found`);
  }

  const scale = getExportScale();

  const canvas = await html2canvas(element, {
    scale,
    useCORS: true,
    allowTaint: false,
    backgroundColor: "#ffffff",
    logging: false,
  });

  const imgData = canvas.toDataURL("image/png");
  const pageWidth = 210; // A4 mm
  const pageHeight = 297;
  const margin = 10;
  const imgAspect = canvas.height / canvas.width;
  const useLandscape = imgAspect > 1;
  const contentWidth = (useLandscape ? pageHeight : pageWidth) - 2 * margin;
  const contentHeight = (useLandscape ? pageWidth : pageHeight) - 2 * margin;
  let yOffset = margin;

  const pdf = new jsPDF({
    orientation: useLandscape ? "landscape" : "portrait",
    unit: "mm",
    format: "a4",
    compress: true,
  });

  const centerX = pdf.internal.pageSize.getWidth() / 2;

  if (options.chartName) {
    pdf.setFontSize(14);
    pdf.text(options.chartName, centerX, yOffset, { align: "center" });
    yOffset += 8;
  }
  if (options.birthDate || options.birthPlace) {
    pdf.setFontSize(10);
    if (options.birthDate) {
      pdf.text(`Birth: ${options.birthDate}`, centerX, yOffset, { align: "center" });
      yOffset += 5;
    }
    if (options.birthPlace) {
      pdf.text(options.birthPlace, centerX, yOffset, { align: "center" });
      yOffset += 8;
    }
  }

  const availableHeight = contentHeight - yOffset - 12;
  const imgHeight = (canvas.height * contentWidth) / canvas.width;
  const scaledHeight = Math.min(imgHeight, availableHeight);
  const scaledWidth = (canvas.width * scaledHeight) / canvas.height;

  pdf.addImage(
    imgData,
    "PNG",
    margin + (contentWidth - scaledWidth) / 2,
    yOffset,
    scaledWidth,
    scaledHeight
  );

  pdf.setFontSize(8);
  pdf.setTextColor(128, 128, 128);
  const footerY = pdf.internal.pageSize.getHeight() - 8;
  pdf.text("Generated by Jyotishya", centerX, footerY, { align: "center" });

  const fileName = options.fileName ?? `birth-chart-${Date.now()}.pdf`;
  pdf.save(fileName);
}

/**
 * Export multi-page report (e.g. KundliReport with PdfPage structure)
 * Wraps existing generatePdf logic with improved error handling
 */
export async function exportReportAsPdf(
  options: ReportExportOptions
): Promise<void> {
  if (!isBrowser()) {
    throw new Error("PDF export requires browser environment");
  }

  const element = document.getElementById(options.elementId);
  if (!element) {
    throw new Error(`Element with ID "${options.elementId}" not found`);
  }

  const pdf = new jsPDF("p", "mm", "a4");
  const pdfWidth = pdf.internal.pageSize.getWidth();
  const pdfHeight = pdf.internal.pageSize.getHeight();
  const pages = Array.from(element.children) as HTMLElement[];

  if (pages.length === 0) {
    throw new Error("No pages found in report root");
  }

  if (pages.length > PDF_LIMITS.MAX_PDF_PAGES) {
    throw new Error(
      `Report exceeds maximum page limit (${PDF_LIMITS.MAX_PDF_PAGES} pages)`
    );
  }

  const scale = getExportScale();

  for (let i = 0; i < pages.length; i++) {
    const page = pages[i];
    if (!(page instanceof HTMLElement)) continue;

    if (i > 0) pdf.addPage();

    const canvas = await html2canvas(page, {
      scale,
      useCORS: true,
      allowTaint: false,
      logging: false,
      backgroundColor: "#ffffff",
    });

    const imgData = canvas.toDataURL("image/png");
    pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight);
  }

  const fileName = options.fileName ?? "report.pdf";
  pdf.save(fileName);
}
